### ISSUE TITLE
BUG: dark theme colours 

### ISSUE THREAD

**Issue by ChidiRnweke** [singiamtel/showcord#33]
1. Switching from dark mode to light mode and vice versa requires a page reload
2. Some colours aren't changed when on dark mode (compared to light) and are thus hard to read

Example:

![image](https://github.com/singiamtel/showcord/assets/88949660/cb5beb6b-7620-47e8-938f-62ffcd153525)

![image](https://github.com/singiamtel/showcord/assets/88949660/5d8ed693-9d5e-4174-a87f-c3b7e0c55f3d)

**Comment by singiamtel** [comment]
Fixed in ea22b14fe5ecc7705aa0ebaba8f424c8ae96eeca and 6fdad651fc27baa8c6118c5c7209a0a261b03363

Thanks for the report!
