### ISSUE TITLE
Warning message barely readable in dark mode

### ISSUE THREAD

**Issue by ThiefMaster** [singiamtel/showcord#35]
![image](https://github.com/singiamtel/showcord/assets/179599/03c168ec-017e-4203-b7c4-ed3525c8d8a9)

Probably it's using the same colors for both color schemes instead of a much lighter version in dark mode.

**Comment by singiamtel** [comment]
Good catch! I'll have to normalize the tailwind theme and shadcn variables at some point, will add it to the to-do list.

Pushed a patch meanwhile in 561162f0b8aef89f75df2f13def0f6e47c6bc403, thanks for reporting!

**Comment by ThiefMaster** [comment]
Looks much better now :)
